package com.matrix.synapse.manager.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme — Matrix-inspired teal/green with warm neutrals
val PrimaryLight = Color(0xFF006B54)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFF7BF5D4)
val OnPrimaryContainerLight = Color(0xFF002119)
val SecondaryLight = Color(0xFF4A6367)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFCDE8EC)
val OnSecondaryContainerLight = Color(0xFF051F22)
val TertiaryLight = Color(0xFF50606E)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFD3E5F5)
val OnTertiaryContainerLight = Color(0xFF0B1D26)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFF6FBF9)
val OnBackgroundLight = Color(0xFF191C1B)
val SurfaceLight = Color(0xFFF6FBF9)
val OnSurfaceLight = Color(0xFF191C1B)
val SurfaceVariantLight = Color(0xFFDAE5E2)
val OnSurfaceVariantLight = Color(0xFF3F4947)
val OutlineLight = Color(0xFF6F7977)
val OutlineVariantLight = Color(0xFFBEC9C6)

// Dark theme
val PrimaryDark = Color(0xFF5DDDB9)
val OnPrimaryDark = Color(0xFF00382C)
val PrimaryContainerDark = Color(0xFF00513F)
val OnPrimaryContainerDark = Color(0xFF7BF5D4)
val SecondaryDark = Color(0xFFB1CCD0)
val OnSecondaryDark = Color(0xFF1C3438)
val SecondaryContainerDark = Color(0xFF334B4F)
val OnSecondaryContainerDark = Color(0xFFCDE8EC)
val TertiaryDark = Color(0xFFB7C9D8)
val OnTertiaryDark = Color(0xFF20323D)
val TertiaryContainerDark = Color(0xFF384955)
val OnTertiaryContainerDark = Color(0xFFD3E5F5)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF191C1B)
val OnBackgroundDark = Color(0xFFE0E3E1)
val SurfaceDark = Color(0xFF191C1B)
val OnSurfaceDark = Color(0xFFE0E3E1)
val SurfaceVariantDark = Color(0xFF3F4947)
val OnSurfaceVariantDark = Color(0xFFBEC9C6)
val OutlineDark = Color(0xFF889391)
val OutlineVariantDark = Color(0xFF3F4947)
